FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# FlowApi


## Flow Plan [/flows/{flow}]
+ Parameters
    + flow: `progressive-profiling` (string, required) - The flow path 

### Get a flow plan [GET]

+ Response 200 (application/json)
        
        {
          "id": "progressive-profile",
          "initial": "idle",
          "states": {
            "idle": {
              "on": {
                "START": {
                  "target": "init"
                }
              }
            },
            "init": {
              "exit": "assignFlowId",
              "invoke": {
                "src": "start_flow",
                "onDone": [
                  {
                    "target": "collect-age"
                  }
                ]
              }
            },
            "collect-age": {
              "initial": "show_screen_set",
              "states": {
                "show_screen_set": {
                  "invoke": {
                    "src": "screen_set",
                    "data": {
                      "screen_set": "Default-ProfileUpdate",
                      "start_screen": "gigya-update-profile-screen"
                    }
                  },
                  "on": {
                    "AFTER-SUBMIT": {
                      "target": "age_condition"
                    }
                  }
                },
                "age_condition": {
                  "invoke": {
                    "src": "transition_api",
                    "id": "age_condition"
                  },
                  "on": {
                    "ADULT": {
                      "target": "#progressive-profile.adult"
                    },
                    "CHILD": {
                      "target": "#progressive-profile.child"
                    }
                  }
                }
              }
            },
            "adult": {
              "initial": "collect_newslatter",
              "states": {
                "collect_newslatter": {
                  "invoke": {
                    "src": "screen_set",
                    "invoke": {
                      "src": "screen_set",
                      "data": {
                        "screen_set": "Default-ProfileUpdate",
                        "start_screen": "gigya-communication-screen"
                      }
                    },
                    "on": {
                      "AFTER-SUBMIT": {
                        "target": "callback"
                      }
                    }
                  },
                  "callback": {
                    "invoke": {
                      "src": "event_emitter",
                      "id": "adult",
                      "onDone": [
                        {
                          "target": "#progressive-profile.completed"
                        }
                      ]
                    }
                  }
                }
              }
            },
            "child": {
              "initial": "collect_child_consent",
              "states": {
                "collect_parent_details": {
                  "invoke": {
                    "src": "screen_set",
                    "data": {
                      "screen_set": "Default-ProfileUpdate",
                      "start_screen": "gigya-privacy-screen"
                    }
                  },
                  "on": {
                    "AFTER-SUBMIT": {
                      "target": "callback"
                    }
                  }
                },
                "callback": {
                  "invoke": {
                    "src": "event_emitter",
                    "data": {
                      "event": "after-child-consent"
                    },
                    "onDone": [
                      {
                        "target": "#progressive-profile.completed"
                      }
                    ]
                  }
                }
              }
            },
            "completed": {
              "invoke": {
                "src": "event_emitter",
                "data": {
                  "event": "progressive-profile-completed"
                }
              }
            }
          }
        }
        

## Flow Dispatcher [/flows/{flow}/start]
+ Parameters
    + flow: `progressive-profiling` (string, required) - The flow path 
    
### Start the flow [POST] 

+ Request (application/json)

    + Attributes
        + source:  `checkout-page` (string)
        + locale: `en` (string)
        
        + Headers
            user-agent: Mozilla/5.0

+ Response 201 (application/json) 
        
    + Attributes (`Basic_Response`)
       + id: GUID (string)
       + state:`collect-age` (string)`
       + _links (object)
            + *self* (object)
               + href: /flows/{flow}/start
       
 

## Flow Inspector [/flows/{flow}/{id}/{activity}]
+ Parameters
    + flow: `progressive-profiling` (string, required) - The flow path 
    + id: `452232832872` (string, required) - The flow id 
    + activity: `#progressive-profile.collect-age` (string, required) - The activity id 


### Transition API [POST]

+ Request (application/json)

    + Attributes
        + event:  `AFTER-SUBMIT` (string)
        
        + Headers
            user-agent: Mozilla/5.0

+ Response 200 (application/json) 

        
    + Attributes (`Basic_Response`)
       + state:`#progressive-profile.collect-age.server_condition` (string)`
       + event (enum) 
         + `ADULT` 
         + `CHILD` (default)
       
       
           
## Data Structures

### `Basic_Response` (object)

+ callId: `778ff47f3e294778bc7df44dfeeff764`
+ errorCode: 0 (number)
+ apiVersion: 2 (number)
+ statusCode: 200
+ statusReason: `OK` (string)
+ time: `2022-05-15T14:47:36.964Z`

### `With_login_token` (object)
+ login_token : `st2.login_token` (string)